const { z } = require("zod");
const { PromptTemplate } = require("@langchain/core/prompts");
const { geminiModel } = require("./geminiClient");

const MAX_INPUT_LENGTH = 1000; // keep the free-text input small (cost + abuse control)
const MAX_SKILLS = 15;
const ABOUT_MAX_LENGTH = 500; // must match the User model's about.maxlength

// Shape we want Gemini to return. LangChain uses this to force the model's
// output into valid JSON matching this exact shape (no manual parsing needed).
const profileSchema = z.object({
  about: z
    .string()
    .describe("A short, professional, first-person bio (2-4 sentences)"),
  skills: z
    .array(z.string())
    .describe("Technical skills mentioned or clearly implied by the input"),
});

// The prompt template. {rawText} gets swapped in with the user's actual
// input each time this is used.
const promptTemplate = PromptTemplate.fromTemplate(
  `You are helping a developer write their profile for a developer-networking app.
Given their rough notes below, write:
1. "about": a short, professional, first-person bio (2-4 sentences, plain text, no markdown)
2. "skills": a list of the technical skills/technologies mentioned or clearly implied

Only use information from the notes. Do not make up skills or achievements that aren't there.

Developer's notes:
"""
{rawText}
"""`
);

// Takes the user's rough text and returns { about, skills } generated by Gemini.
const generateProfileFromText = async (rawText) => {
  const trimmedText = (rawText || "").trim();

  if (!trimmedText) {
    throw new Error("Please enter some text about yourself first.");
  }
  if (trimmedText.length > MAX_INPUT_LENGTH) {
    throw new Error(`Please keep it under ${MAX_INPUT_LENGTH} characters.`);
  }

  // Attach the schema to the model so the response comes back as clean JSON.
  const structuredModel = geminiModel.withStructuredOutput(profileSchema);

  const prompt = await promptTemplate.format({ rawText: trimmedText });

  let result;
  try {
    result = await structuredModel.invoke(prompt);
  } catch (error) {
    if (error.status === 429) {
      throw new Error("AI generation is rate-limited right now (free tier quota). Please try again in a bit.");
    }
    throw error;
  }

  // Don't fully trust the model — clean up the result ourselves too.
  const cleanedSkills = (result.skills || [])
    .map((skill) => skill.trim())
    .filter((skill) => skill.length > 0)
    .slice(0, MAX_SKILLS);

  const cleanedAbout = (result.about || "").trim().slice(0, ABOUT_MAX_LENGTH);

  return { about: cleanedAbout, skills: cleanedSkills };
};

module.exports = { generateProfileFromText };
